### ISSUE TITLE
VPS Issue

### ISSUE THREAD

**Issue by ColegoneCrazy** [Kon-UU/Ro-Sniper-python#13]
Whenever I run the program on my computer it works fine. The problem is I don’t want to burn my computer up. I want to use a vps but whenever I transfer the code into a new vps it just says “Cookie error”. I’ve installed all the requirements including requests, dotenv, and python 3.9 in  3 different vps’s but still the same issue. I even went as far as adding my dotenv stuff into the actual code and deleting that but still the same problem

Any help?

Thanks

**Comment by ColegoneCrazy** [comment]
> I tested this on my linux vps and it works fine maybe changing your vps locale to en.US could if it

Can you provide me with all the pip installs on your vps? My vps is already en.us. (command bar => pip list)

**Comment by ColegoneCrazy** [comment]
C:\Users\Administrator\Desktop\Ro-Sniper-python-main2\Ro-Sniper-python-main>python main.py
Loaded 3, 1, 1000
Ro-Sniper Python by Kon_UU
Exception in thread XSRF_Worker_1:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
Cookie error
    self.run()
  File "C:\Users\Administrator\Desktop\Ro-Sniper-python-main2\Ro-Sniper-python-main\main.py", line 84, in run
    conn.request("POST", "/v2/login", headers={"Cookie": f".ROBLOSECURITY={ROBLOX_TOKEN}"})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 980, in send
    self.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)


This is my command prompt rn. Btw I'm in a windows vps
